### ISSUE TITLE
 Update zendframework/zend-mvc

### ISSUE THREAD

**Issue by sOOrf** [ZF-Commons/ZfcUser#625] opened 2016-03-04 14:01 UTC
After update zendframework/zend-mvc from 2.6.2 -> 2.7.1 
Stop working.

**Comment by dymen1** [comment] 2016-03-07 10:35
duplicate of https://github.com/ZF-Commons/ZfcUser/issues/623

**Comment by Danielss89** [comment] 2016-05-05 19:25
Fixed in #637

**Closed by Danielss89** 2016-05-05 19:25 UTC
