### ISSUE TITLE
No longer works with doctrine-orm-module master

### ISSUE THREAD

**Issue by jarrettj** [ZF-Commons/ZfcUser#586] opened 2015-05-08 09:46 UTC
Hi,

Using doctrine/doctrine-orm-module master no longer works with zf-commons/zfc-user. I get the following error from composer:

```
Problem 1
    - zf-commons/zfc-user-doctrine-orm 1.0.0 requires doctrine/doctrine-orm-module 0.* -> no matching package found.
    - zf-commons/zfc-user-doctrine-orm 1.0.0 requires doctrine/doctrine-orm-module 0.* -> no matching package found.
    - Installation request for zf-commons/zfc-user-doctrine-orm 1.* -> satisfiable by zf-commons/zfc-user-doctrine-orm[1.0.0].
```

But I know this has worked before. I use the master branch to enable 2nd level cache in doctrine using ZF2.

Any help please.

Thanks.

**Comment by Ocramius** [comment] 2015-05-08 09:58
`doctrine/doctrine-orm-module` `0.*` is available as per https://packagist.org/packages/doctrine/doctrine-orm-module

Closing as invalid - the problem is not here.

**Closed** 2015-05-08 11:53 UTC

**Comment by jarrettj** [comment] 2015-05-08 12:55
Cool. Thanks. You can close this then. Cheers.
